'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, CalendarDays, ChevronDown, Compass, FileText, Menu, Mic2, Play, Quote, Sparkles, Users, X } from 'lucide-react'

const images = {
  logo: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/logo_natangue-2IM9MiSyDzWrybge14tmFVQlk28MHE.png',
  portrait: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/484896858_623781817288050_8840694130311934692_n-T7dKopqiL9TWQaVMAxyUamET9PNmMs.jpg',
  speaking: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/627369292_888061987526697_8452311760145747511_n-XDVGoSwXqu0xHQhaXSLEwqZcMmVYpN.jpg',
  forum: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/727519297_997071459959082_4157106646371115466_n-iH3AYFpBjXBk1snmlLMeymQQSeVU41.jpg',
}

const navItems = [
  ['Le leader', '/leader'], ['Le programme', '/programme'], ['Feuille de route', '/feuille-de-route'], ['Discours', '/discours'], ['Actualités', '/actualites'], ['Agenda', '/agenda'],
]

const pillars = [
  { icon: Compass, label: 'Feuille de route', text: 'Une vision lisible, construite avec les réalités du terrain.', href: '/feuille-de-route', tone: 'gold' },
  { icon: Users, label: 'Le programme', text: 'Des engagements structurés autour des priorités citoyennes.', href: '/programme', tone: 'green' },
  { icon: Mic2, label: 'Les prises de parole', text: 'Retrouver les discours, interviews et messages publics.', href: '/discours', tone: 'blue' },
]

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [videoOpen, setVideoOpen] = useState(false)

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key !== 'Escape') return
      setVideoOpen(false)
      setMenuOpen(false)
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [])

  return (
    <main className="min-h-dvh overflow-hidden bg-[#f7f8f2] text-[#14352b]">
      <div className="bg-[#14352b] px-4 py-2 text-center text-[10px] font-medium leading-relaxed tracking-[0.08em] text-[#f5c84c] sm:px-5 sm:text-[11px] sm:tracking-[0.12em]">NATANGUER · TEUGHETTHIE SOUGNOU YITÉE</div>
      <header className="sticky top-0 z-40 border-b border-[#14352b]/10 bg-[#f7f8f2]/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-5 py-4 lg:px-8">
          <Link href="/" className="flex min-w-0 items-center gap-3" aria-label="NATANGUER accueil"><img src={images.logo} alt="Logo NATANGUER" className="h-12 w-12 shrink-0 rounded-full object-cover" /><span className="truncate text-lg font-bold tracking-[-0.04em]">NATANGUER</span></Link>
          <nav className="hidden items-center gap-7 lg:flex">{navItems.map(([label, href]) => <Link key={href} href={href} className="text-sm font-medium text-[#14352b]/70 transition hover:text-[#14352b]">{label}</Link>)}<Link href="/qr/flyer-rufisque" className="rounded-full bg-[#f5c84c] px-5 py-3 text-sm font-bold text-[#14352b] shadow-sm transition hover:-translate-y-0.5">Accès rapide</Link></nav>
          <button className="-mr-2 grid h-11 w-11 shrink-0 place-items-center rounded-full transition hover:bg-[#14352b]/5" aria-expanded={menuOpen} aria-controls="menu-mobile" aria-label={menuOpen ? 'Fermer le menu' : 'Ouvrir le menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
        </div>
        {menuOpen && <div id="menu-mobile" className="max-h-[calc(100dvh-4rem)] overflow-y-auto border-t border-[#14352b]/10 bg-[#f7f8f2] px-5 py-4 lg:hidden">{navItems.map(([label, href]) => <Link onClick={() => setMenuOpen(false)} key={href} href={href} className="block border-b border-[#14352b]/10 py-3 text-sm font-semibold">{label}</Link>)}<Link href="/qr/flyer-rufisque" className="mt-4 block rounded-full bg-[#f5c84c] px-5 py-3 text-center text-sm font-bold">Découvrir le flyer</Link></div>}
      </header>

      <section className="relative mx-auto grid max-w-7xl items-center gap-8 px-5 pb-16 pt-10 sm:gap-12 sm:pt-14 lg:grid-cols-[1.02fr_.98fr] lg:px-8 lg:pb-28 lg:pt-24">
        <div className="relative z-10 order-2 lg:order-1"><p className="mb-6 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#27824d]"><span className="h-2 w-2 rounded-full bg-[#f5c84c]" /> Mouvement citoyen · Rufisque</p><h1 className="max-w-2xl text-[clamp(3.5rem,8vw,7rem)] font-semibold leading-[.89] tracking-[-0.08em]">Construire <em className="font-serif font-normal text-[#27824d]">ensemble.</em></h1><p className="mt-8 max-w-lg text-lg leading-relaxed text-[#14352b]/65">Une plateforme pour comprendre la vision, suivre les engagements et participer à la construction de notre territoire.</p><div className="mt-9 flex flex-col items-stretch gap-3 sm:flex-row sm:flex-wrap sm:items-center"><Link href="/programme" className="inline-flex min-h-[44px] items-center justify-center gap-3 rounded-full bg-[#14352b] px-6 py-4 text-center text-sm font-bold text-white transition hover:bg-[#27824d]">Découvrir le programme <ArrowRight size={16} /></Link><button onClick={() => setVideoOpen(true)} className="inline-flex min-h-[44px] items-center justify-center gap-3 rounded-full border border-[#14352b]/20 px-6 py-4 text-center text-sm font-bold transition hover:border-[#14352b]"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#f5c84c]"><Play size={12} fill="currentColor" /></span> Voir la présentation</button></div><div className="mt-10 flex flex-wrap items-center gap-x-6 gap-y-2 border-t border-[#14352b]/15 pt-6 sm:gap-x-8"><div><p className="text-2xl font-bold">01</p><p className="text-xs text-[#14352b]/55">Vision partagée</p></div><div className="h-8 w-px bg-[#14352b]/15" /><div><p className="text-2xl font-bold">03</p><p className="text-xs text-[#14352b]/55">Priorités citoyennes</p></div></div></div>
        <div className="relative order-1 mx-auto w-full max-w-[540px] lg:order-2 lg:ml-auto"><div className="absolute -right-5 -top-5 h-28 w-28 rounded-full border border-[#f5c84c] lg:h-40 lg:w-40" /><div className="relative aspect-[.82] overflow-hidden rounded-[2rem] bg-[#d9e0d8] shadow-2xl shadow-[#14352b]/15"><img src={images.portrait} alt="Adama Dienne, portrait officiel" className="h-full w-full object-cover object-center" /><div className="absolute inset-0 bg-gradient-to-t from-[#14352b]/70 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 text-white"><p className="font-serif text-2xl italic">Adama Dienne</p><p className="mt-1 text-xs uppercase tracking-[0.16em] text-white/70">Président du mouvement</p></div></div><div className="absolute -bottom-8 -left-5 rounded-2xl bg-[#f5c84c] px-5 py-4 shadow-xl"><p className="font-serif text-xl italic">Teughetthei</p><p className="text-[10px] font-bold uppercase tracking-[0.12em]">Sougnou yitéé</p></div></div>
      </section>

      <section className="bg-[#14352b] px-5 py-20 text-white lg:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#f5c84c]">Notre cap</p><h2 className="mt-4 max-w-md text-4xl font-semibold tracking-[-0.05em] lg:text-6xl">La politique au service du quotidien.</h2></div><p className="max-w-lg text-lg leading-relaxed text-white/65">NATANGUER porte une démarche de proximité, d’écoute et d’action. Cette plateforme rassemble les contenus publics du mouvement, dans un esprit de clarté et de responsabilité.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{pillars.map(({ icon: Icon, label, text, href, tone }) => <Link href={href} key={label} className="group rounded-3xl border border-white/15 bg-white/[.04] p-6 transition hover:-translate-y-1 hover:bg-white/[.09]"><div className={`mb-8 grid h-11 w-11 place-items-center rounded-2xl md:mb-14 ${tone === 'gold' ? 'bg-[#f5c84c] text-[#14352b]' : tone === 'blue' ? 'bg-[#a7c9dc] text-[#14352b]' : 'bg-[#73b65c] text-[#14352b]'}`}><Icon size={20} /></div><h3 className="text-xl font-semibold">{label}</h3><p className="mt-2 text-sm leading-relaxed text-white/55">{text}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#f5c84c]">Explorer <ArrowRight size={14} className="transition group-hover:translate-x-1" /></span></Link>)}</div></div></section>

      <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:px-8 lg:py-28"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#27824d]">Le leader</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] lg:text-6xl">Une parole qui relie.</h2><p className="mt-6 max-w-md text-base leading-relaxed text-[#14352b]/65">Découvrez le parcours et les prises de parole d&apos;Adama Dienne, ainsi que les convictions qui nourrissent son engagement.</p><Link href="/leader" className="mt-8 inline-flex min-h-[44px] items-center gap-2 text-sm font-bold text-[#27824d]">Rencontrer le leader <ArrowRight size={16} /></Link><blockquote className="mt-10 border-l-2 border-[#f5c84c] pl-5 md:mt-14"><Quote className="mb-3 text-[#f5c84c]" size={22} fill="currentColor" /><p className="font-serif text-2xl italic leading-snug">« L&apos;action citoyenne commence par l&apos;écoute et la constance. »</p><cite className="mt-3 block text-xs font-bold not-italic uppercase tracking-[0.15em] text-[#14352b]/50">Adama Dienne · Rufisque</cite></blockquote></div><div className="grid grid-cols-2 gap-3"><div className="relative col-span-2 aspect-[1.8] overflow-hidden rounded-[1.5rem]"><img src={images.speaking} alt="Adama Dienne présentant sa vision lors d'une cérémonie" className="h-full w-full object-cover" /><div className="absolute inset-x-4 bottom-4 flex items-end justify-between rounded-2xl bg-[#14352b]/85 p-4 text-white backdrop-blur-sm"><div><p className="font-serif text-xl italic">Adama Dienne</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[0.14em] text-white/65">Président du mouvement NATANGUER</p></div><Link href="/leader" className="inline-flex min-h-[44px] items-center justify-center rounded-full bg-[#f5c84c] px-4 py-2 text-xs font-bold text-[#14352b]">Son parcours</Link></div></div><div className="aspect-square overflow-hidden rounded-[1.5rem]"><img src={images.forum} alt="Adama Dienne lors d'une rencontre citoyenne" className="h-full w-full object-cover object-center" /></div><div className="flex aspect-square flex-col justify-between rounded-[1.5rem] bg-[#f5c84c] p-5"><Sparkles size={22} /><p className="font-serif text-2xl italic leading-tight">Une démarche locale, une ambition collective.</p><Link href="/temoignages" className="text-xs font-bold uppercase tracking-[0.14em]">Voir les témoignages →</Link></div></div></section>

      <section className="border-y border-[#14352b]/10 bg-[#edf1e9] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#27824d]">À la une</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.05em]">Suivre le mouvement</h2></div><Link href="/actualites" className="inline-flex min-h-[44px] items-center text-sm font-bold text-[#27824d]">Toutes les actualités <ArrowRight className="ml-1 inline" size={15} /></Link></div><div className="mt-10 grid gap-4 md:grid-cols-3"><Link href="/discours" className="rounded-3xl bg-white p-6 transition hover:-translate-y-1"><FileText className="text-[#27824d]" /><p className="mt-8 text-xs font-bold uppercase tracking-[0.15em] md:mt-14 text-[#14352b]/45">Prise de parole</p><h3 className="mt-2 text-xl font-semibold">Retrouver les discours et messages</h3></Link><Link href="/agenda" className="rounded-3xl bg-[#14352b] p-6 text-white transition hover:-translate-y-1"><CalendarDays className="text-[#f5c84c]" /><p className="mt-8 text-xs font-bold uppercase tracking-[0.15em] md:mt-14 text-white/45">Agenda</p><h3 className="mt-2 text-xl font-semibold">Les prochains rendez-vous citoyens</h3></Link><Link href="/qr/flyer-rufisque" className="rounded-3xl bg-[#f5c84c] p-6 transition hover:-translate-y-1"><ChevronDown className="text-[#14352b]" /><p className="mt-8 text-xs font-bold uppercase tracking-[0.15em] md:mt-14 text-[#14352b]/50">Accès direct</p><h3 className="mt-2 text-xl font-semibold">Scannez. Découvrez. Participez.</h3></Link></div></div></section>

      <footer className="bg-[#14352b] px-5 py-10 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-end"><div><div className="flex items-center gap-3"><img src={images.logo} alt="Logo NATANGUER" className="h-12 w-12 rounded-full" /><span className="text-lg font-bold">NATANGUER</span></div><p className="mt-4 max-w-xs text-sm leading-relaxed text-white/50">Teughetthei sougnou yitéé — notre avenir partagé.</p></div><div className="flex flex-wrap items-center gap-x-6 gap-y-1 text-sm text-white/65">{navItems.slice(0, 4).map(([label, href]) => <Link key={href} href={href} className="inline-flex min-h-[44px] items-center hover:text-[#f5c84c]">{label}</Link>)}<Link href="/admin" className="inline-flex min-h-[44px] items-center hover:text-[#f5c84c]">Espace démo</Link></div></div><div className="mx-auto mt-10 max-w-7xl border-t border-white/10 pt-5 text-xs text-white/35">Prototype de démonstration · Contenus officiels à compléter</div></footer>
      {videoOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-[#14352b]/80 p-4 backdrop-blur-sm sm:p-5" role="dialog" aria-modal="true" aria-label="Présentation NATANGUER" onClick={() => setVideoOpen(false)}><div className="relative max-h-[85dvh] w-full max-w-lg overflow-y-auto rounded-3xl bg-[#f7f8f2] p-6 sm:p-8" onClick={(event) => event.stopPropagation()}><button onClick={() => setVideoOpen(false)} className="absolute right-4 top-4 grid h-11 w-11 place-items-center rounded-full hover:bg-black/5 sm:right-5 sm:top-5" aria-label="Fermer"><X size={20} /></button><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#27824d]">Présentation</p><h2 className="mt-3 pr-8 text-2xl font-semibold sm:text-3xl">NATANGUER en quelques mots</h2><p className="mt-4 leading-relaxed text-[#14352b]/65">Cette vidéo de présentation est un emplacement de démonstration. Les contenus audiovisuels officiels seront ajoutés ultérieurement.</p><button onClick={() => setVideoOpen(false)} className="mt-7 inline-flex min-h-[44px] w-full items-center justify-center rounded-full bg-[#14352b] px-5 py-3 text-sm font-bold text-white sm:w-auto">Fermer la présentation</button></div></div>}
    </main>
  )
}
